### ISSUE TITLE
Use your Kanban

### ISSUE THREAD

**Issue by yukicruz** [jmacost5/CPP-528-Project#105]
@jmacost5, @mrowland1, @krbrick, @Rached-ASU, @Ma112120:

Your Kanban is not being utilized. All your cards are in the To Do Column. There should be several cards from Week 1 and 2 already in the Doing or Done Columns.

Reference [Lab01 Instruction](https://watts-college.github.io/cpp-528-spr-2022/labs/lab-01-instructions/):

> ...
> 6. Brainstorm project tasks with your team for the coming week and add all of the cards to To Do
> 7. Assign immediate tasks to each person, add their names to their cards, and move to Doing
> 8. Update the board each week with completed tasks, new assignments, and new tasks

Examples of project-related cards that could be created for Week 1 and 2 include:
* Make a Kanban board
* Set up data structure
* Download data concordance file
* Upload X file(s)
* etc.

Assign cards to yourself or others. Assign reviewers if needed.

Accustom yourselves to using the Kanban board effectively, otherwise the required tasks of the final project will overwhelmingly pile up before you know it and essential tasks will fall through the cracks.

**Comment by yukicruz** [comment]
I wanted to note that your team has been doing well with closing out resolved issues. Once you start adding weekly tasks more regularly, however, consider leaving Completed Cards in the Done Column at least until the end of a Lab so teammates can easily reference them and not accidentally duplicate efforts.

If you're new to it, asynchronous teamwork has a different tempo and movement. It definitely takes some getting used to. This course is a great place to learn and become familiar with it.

**Comment by mrowland1** [comment]
Regularly using Kanban
