### ISSUE TITLE
Add raw files to "raw" folder.

### ISSUE THREAD

**Issue by yukicruz** [jmacost5/CPP-528-Project#109]
@jmacost5, @mrowland1, @krbrick, @Rached-ASU, @Ma112120:

Add raw files from Lab02 to "raw" folder. 

This issue should be assigned a team member and assigned to the project.

**Comment by yukicruz** [comment]
Well done adding Lab03 raw files to the raw folder. Please continue adding raw files for future labs and remember to add Lab02 raw files.

**Comment by mrowland1** [comment]
raw files have been added
