### ISSUE TITLE
Put "labs" folder at same level as "data" folder

### ISSUE THREAD

**Issue by yukicruz** [jmacost5/CPP-528-Project#115]
@mrowland1,

I noticed in the "lab03_labsfolder_mr" branch that the _labs_ folder is a child folder under the _data_ folder. See [Wk02 Lab ](https://watts-college.github.io/cpp-528-spr-2022/labs/lab-02/) for the example tree.

If you plan to merge the "lab03_labsfolder_mr" branch into the main branch, please check that you're placing folders in your preferred levels before merging your branch into the main branch.

Trimmed down example tree:

├── data
│   ├── README.md
│   ├── raw
│   │   ├── README.md
│   ├── rodeo
│   │   └── README.md
│   └── wrangling
│       └── README.md
├── labs
│   ├── wk01
│       └── README.md
│   ├── wk02
│       └── README.md
│   ├── wk03
│       └── README.md

**Comment by mrowland1** [comment]
Moved and complete
