### ISSUE TITLE
Clear out old branches

### ISSUE THREAD

**Issue by yukicruz** [jmacost5/CPP-528-Project#116]
@jmacost5, @krbrick, @mrowland1, @Rached-ASU, @Ma112120:

After merging branches with the main branch or realizing you no longer need a branch for whatever reason, delete the unneeded branch to limit clutter in your branches list.

This isn't a particularly time-sensitive issue and I acknowledge some technical issues are currently being worked on which may temporarily increase the number of branches in existence. Erroneous branches, however, will need to be removed before the final project is finalized at the latest. It is generally a good practice to remove unnecessary branches so try becoming accustomed to the practice early on.

**Comment by mrowland1** [comment]
Completed
