### ISSUE TITLE
a table of contents

### ISSUE THREAD

**Issue by jmacost5** [jmacost5/CPP-528-Project#74]
Executive Summary (4-6 sentences)
Overview / Research Question Program Details
Data
Methods
Results
Part I: Neighborhood Change
Metrics
Data sources
Median Home Value
Gentrification
Descriptive Analysis of Neighborhood Change
Average change in MHV from 2000 to 2010
Predicting Change Based on 2000 Neighborhood characteristics
Neighborhood demographics
Spatial characteristics (population density, adjacent tracts)
Part II: Evaluation of Tax Credits
Overview of Programs
New Market Tax Credits
Low Income Housing Tax Credits
Data sources
Descriptive Statistics
Dollars given out
Characteristics of neighborhoods that received them
Characteristics of those that did not
Predictive Analysis
Aggregate credits given between 2000 and 2010
Update models by adding tax credit amounts
Part III – Results and Conclusion
Note that there are some sections like “Overview of Programs” that require a succinct narrative for context. But most of the sections will focus on describing the methodology to the audience and walking them through the process of generating results. These chapters will have more of a tutorial or code- through feel than a final report tone. The goal of those sections is to make the methodology as transparent as possible and to make it easy for others to reproduce the work and extend it

**Comment by mrowland1** [comment]
created table of contents on GitHub website
